# Generated by Django 4.2.8 on 2025-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="last_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
    ]